# Generated by Django 5.2.6 on 2025-09-22 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='movies.genre'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollowing',
            index=models.Index(fields=['user', 'followed_user'], name='user_follow_user_id_9b35f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollowing',
            index=models.Index(fields=['created_at'], name='user_follow_created_b74ebf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'followed_user')},
        ),
    ]
