# Generated by Django 5.2.6 on 2025-09-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
    ]
